services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    networks:
      - vr-networks

      
  backend-api:
    image: rfauzi/vehicle-rental-api:latest
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - vr-networks

networks:
  vr-networks:
    driver: bridge